/**
 * LLM 深度分析层
 * - Uses OpenAI when OPENAI_API_KEY is set.
 * - Falls back to DeepSeek when DEEPSEEK_API_KEY is set.
 * - Soft-launch default provider is DeepSeek, because it is cheaper to validate.
 * - 定位: 规则引擎预过滤 → LLM 只对有问题的代码生成修复建议
 * - 所有 AI 修复建议标注 "Generated by AI, verify before applying"
 */

export type LLMScanMode = "standard" | "deep";

interface LLMIssue {
  type: "security" | "quality";
  severity: "critical" | "warning" | "info";
  file: string;
  line: number;
  endLine?: number;
  message: string;
  ruleId: string;
  fixSuggestion: string;
  fixCode?: string;
  codeSnippet?: string;
  referenceUrl?: string;
  aiGenerated?: boolean;
  falsePositive?: boolean;
}

interface LLMAnalysisInput {
  code: string;
  language: string;
  issues: LLMIssue[];
  mode: LLMScanMode;
}

interface LLMAnalysisOutput {
  issues: LLMIssue[];
  modelUsed?: string;
  error?: string;
}

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY;
const LLM_TIMEOUT_MS = 15000;

const MODEL_CONFIG = {
  standard: {
    openai: "gpt-4o-mini",
    deepseek: "deepseek-v4-flash",
  },
  deep: {
    openai: "gpt-4o",
    deepseek: "deepseek-v4-pro",
  },
};

export function hasLLMProvider(): boolean {
  return Boolean(OPENAI_API_KEY || DEEPSEEK_API_KEY);
}

function buildPrompt(input: LLMAnalysisInput): string {
  const { code, language, issues, mode } = input;
  const issueSummary = issues
    .map(
      (i, idx) =>
        `${idx + 1}. [${i.severity}] Line ${i.line}: ${i.message} (rule: ${i.ruleId})`
    )
    .join("\n");

  const modeDesc = mode === "deep"
    ? "Thorough analysis: carefully review each issue, check for false positives, and provide detailed, production-ready fix suggestions with full code examples."
    : "Fast analysis: provide concise, accurate fix suggestions for each confirmed issue. Skip if the issue looks like a false positive.";

  return `You are a senior code security reviewer. Analyze the following ${language} code and the issues already found by static analysis tools.

${modeDesc}

CODE:
\`\`\`${language}
${code.slice(0, 8000)}
\`\`\`

ISSUES FOUND BY STATIC ANALYSIS:
${issueSummary}

For each issue that is NOT a false positive, provide:
1. line number
2. a clear explanation of why it's a problem
3. a concrete fix suggestion with code
4. mark as "ai_enhanced"

For issues that ARE false positives, mark them as "false_positive" and explain why.

Output strictly as JSON array:
[
  {
    "line": 42,
    "severity": "critical|warning|info",
    "message": "Clear explanation",
    "fixSuggestion": "Description of the fix",
    "fixCode": "actual code snippet",
    "aiEnhanced": true,
    "falsePositive": false
  }
]

Rules:
- ONLY output the JSON array, no markdown, no explanations outside JSON
- Do NOT invent issues that are not in the static analysis list
- Do NOT hallucinate APIs or functions that don't exist
- If unsure, mark as false_positive rather than inventing a problem
- All fix suggestions must be syntactically valid ${language} code
`;
}

async function callOpenAI(
  prompt: string,
  mode: LLMScanMode
): Promise<{ content: string; model: string } | null> {
  if (!OPENAI_API_KEY) return null;

  const model = MODEL_CONFIG[mode].openai;
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: "You are a precise code security reviewer. Output only valid JSON." },
        { role: "user", content: prompt },
      ],
      temperature: 0.2,
      max_tokens: mode === "deep" ? 4096 : 2048,
    }),
    signal: AbortSignal.timeout(LLM_TIMEOUT_MS),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "Unknown error");
    throw new Error(`OpenAI API ${res.status}: ${text.slice(0, 200)}`);
  }

  const data = await res.json();
  const content = data.choices?.[0]?.message?.content;
  if (!content) throw new Error("OpenAI returned empty content");

  return { content, model };
}

async function callDeepSeek(
  prompt: string,
  mode: LLMScanMode
): Promise<{ content: string; model: string } | null> {
  if (!DEEPSEEK_API_KEY) return null;

  const model = MODEL_CONFIG[mode].deepseek;
  const res = await fetch("https://api.deepseek.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${DEEPSEEK_API_KEY}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: "You are a precise code security reviewer. Output only valid JSON." },
        { role: "user", content: prompt },
      ],
      temperature: 0.2,
      max_tokens: mode === "deep" ? 4096 : 2048,
    }),
    signal: AbortSignal.timeout(LLM_TIMEOUT_MS),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "Unknown error");
    throw new Error(`DeepSeek API ${res.status}: ${text.slice(0, 200)}`);
  }

  const data = await res.json();
  const content = data.choices?.[0]?.message?.content;
  if (!content) throw new Error("DeepSeek returned empty content");

  return { content, model };
}

function parseLLMResponse(raw: string): LLMIssue[] {
  // 尝试提取 JSON 数组（LLM 可能包裹在 markdown code block 中）
  const jsonMatch = raw.match(/\[[\s\S]*\]/);
  if (!jsonMatch) {
    throw new Error("No JSON array found in LLM response");
  }

  try {
    const parsed = JSON.parse(jsonMatch[0]);
    if (!Array.isArray(parsed)) {
      throw new Error("LLM response is not an array");
    }
    return parsed;
  } catch (_e: unknown) {
    // 尝试清理常见 LLM 格式问题后重新解析
    const cleaned = jsonMatch[0]
      .replace(/,\s*([\]}])/g, "$1") // 去除尾随逗号
      .replace(/\n/g, " ");
    return JSON.parse(cleaned);
  }
}

export async function runLLMAnalysis(
  input: LLMAnalysisInput
): Promise<LLMAnalysisOutput> {
  const prompt = buildPrompt(input);

  // 1. 尝试 OpenAI
  let result: { content: string; model: string } | null = null;
  let modelUsed = "unknown";

  try {
    result = await callOpenAI(prompt, input.mode);
    if (result) modelUsed = result.model;
  } catch (openaiErr) {
    console.error("OpenAI failed, trying DeepSeek fallback:", openaiErr);
  }

  // 2. OpenAI 失败 → 自动切换 DeepSeek
  if (!result) {
    try {
      result = await callDeepSeek(prompt, input.mode);
      if (result) modelUsed = result.model;
    } catch (deepseekErr) {
      console.error("DeepSeek fallback also failed:", deepseekErr);
      return {
        issues: [],
        error: "AI analysis temporarily unavailable. Showing rule-engine results only.",
      };
    }
  }

  if (!result) {
    return {
      issues: [],
      error: "AI analysis temporarily unavailable. Showing rule-engine results only.",
    };
  }

  // 3. 解析 LLM 输出
  let parsed: LLMIssue[];
  try {
    parsed = parseLLMResponse(result.content);
  } catch (parseErr) {
    console.error("Failed to parse LLM response:", parseErr, "Raw:", result.content.slice(0, 500));
    return {
      issues: [],
      error: "AI analysis response malformed. Showing rule-engine results only.",
    };
  }

  // 4. 转换为内部 Issue 格式
  const llmIssues: LLMIssue[] = parsed
    .filter((item) => !item.falsePositive) // 过滤掉 LLM 认为是误报的项目
    .map((item) => ({
      type: "security" as const,
      severity: item.severity || "warning",
      file: "input",
      line: item.line || 0,
      endLine: item.line || 0,
      message: item.message || "AI-generated suggestion",
      ruleId: `llm-${input.mode}-${modelUsed}`,
      fixSuggestion: `${item.fixSuggestion || ""}\n\nGenerated by AI, verify before applying.`,
      fixCode: item.fixCode || undefined,
      codeSnippet: undefined,
      referenceUrl: undefined,
      aiGenerated: true,
    }));

  return { issues: llmIssues, modelUsed };
}
